'''
Given two strings s and t of equal length, the Hamming distance between s and t, denoted dH(s,t), 
is the number of corresponding symbols that differ in s and t. See Figure 2.

Given: Two DNA strings s and t of equal length (not exceeding 1 kbp).

Return: The Hamming distance dH(s,t).
'''

import sys

def dH(s, t):
    if len(s) != len(t):
        print("Error: The two input DNA sequence are of different length. Exiting system.")
        sys.exit()
    try:
        count = 0
        for a, b in zip(s,t):
            if a.upper() != b.upper():
                count += 1
        return count
    except TypeError:
        print("TypeError: Input should be string")


# test1
# output should be 7
x = "GAGCCTACTAACGGGAT"
y = "CATCGTAATGACGGCCT"
dH(x,y)

# test2
# x and y are of different length, the function should print error message and exit system
x = "ccttcaagaggccgtcaaaagagcaaaagatagatctgtaaccacaagattcatcttacaccgtctcgaagctacaatcgatactatcactccgttgattgttaaaattgataagttgagtgaaaaaatggaagattcatcatcgaggaaattcaatgaacgtcttaagcttctccttgtgaacgctgtttctcttgttgaggagaatgcggagctgagacgcagaaacgtacgcaagaagttcaggtttgtgctaaatagttcctatatgtgatttccataaactcccaacagtactaaatctatcaaaacctaacatttactatgaattaagtcaataacatgtgtattatatttgtgttgtttatctttaggtacatgagagatatcaaagagttcgaagctaagatacgatgggtggtaggtgtggatgttcaagttaatcaattggctgatatcaaagaactcaaggccaagatgtctgaaatcagcactaaacttgacaaaataatgcctcaaccgaagtcctccacgaggccgtcaaaagagcaaaagatagatctgtaaccacaagattcatcttacaccgtctcgaagctacaatcgatagtatcacaccgttggtggttcaaattgataagttcagtgaagaaatggaagattcaacatcgaggaaagtcaataaacgtcttaagcttctccttgagaacgctgtttctcttgttgaggagaatgcggagctgagacgcagaaacgtacgcaagaagttcaggtttgtgctaaatagttcctatatgtgatttccataaactcccaacagtactaaatctatcaaaacctaacatttactatgaattaagtcaataacatgtgtattatatttgtgttgtttatctttaggtacatgagagatatcaaagagttcgaagctaaattacgatgggtggtagatgtggatgttcaagttaatcaattggctgatatcaaagaactcaaggccaagatgtctgaaatcagcactaaacttgacaaaataatgcctcaaccgaagt"
y = "gattggtgagcttgcgataggggctgttcttggagttggagcccaagccatttacgaccgcttcagaaaagcaagagatatatctttcgtacaccgtctctgcgctacaatccttagtatcgagccgtttttggttcaaatcgataagcggagtaaagtggaaggttcaccattaagggaagtcaacgaacgtctcacgtgtttccttgaattagcttatgtttttgttgaggcttatccgaaactcagacgcagacaagtactcaggaagtacaggttcgtatatatgacatgaatttctattggtttttggatcgcttaatttcttagtttaatggtttagagaaaaatatcttcttatttgtaacaattttttttacatgatttcgataatctccaaacactaaacgtacaaaacctatcatgttgtggaaaaataacacgtgtattatgtttgttctgtttatctttaggtacatcaaagcaatcgaaacgatagaacttgcattaagaagcataatagttgtggattttcaagttgatcaatgggacgatatcaaagaaatcaaggccaagatatctgaaatggacactaaacttgctgaagttatttctgcttgtagtaaaataagagcttgattaaaaaaaacagagactttgttgaaattatttcttcttgtaatcaatttcggaaatctatttctctctctctcttattccccataattattgaaaaactctttctcaatctatgtgtaattttatcaaaataataattaacaataatctttttatttcgtttcttttgagatctatgtttcatgatttttttttttttttgcataaattgaattaaattaactttgaaagacttgagtttaatgatgtttttactgacaatgatctaaaattgactttaaactatttgatttaattagctacaaaaaagtaaaagactatttaattttgttatttttagttgaattattaataatcatgtattgtttgtgatattaattatacttttgatatgatataatatttaactatttattaatatatattcgcttccaacgcataccgtttattaaattttttattaaaaaaatcgctttcacatttctagacgtttggctaccgcgtacatgcatctaattgcatggtacttcgttaccaagcggtccacacatctcttattcacactctttcgtaggaagttacggtaacaaataacatcccttgactgtacaaactacacggtttaattgttaagcaaaagactcttcaatagttccatgttcataaatttctccttacattcacctcagagagctaacaaactaatttcaagaagatgattgctgaggttgtggcagggggtgctcttggacttgctctcggtgtccttcacgaggccgtcaaaacagcaaaagatagatctgtaaccacaagattcatcttacaccgtctcgaagctacaatcgatagtatcactccgttggtggttcaaattgataagttcagtgaagaaatggaagattcatcatcgaggaaagtcagtgaacgtcttaagcttctccttgagaacgctgtttctcttgttgaggagaatgcggagctgagacgcagaaacgtacgcaagaagttcaggtttgtatatattacatgaaaatccatgtatttctattggttttttatatatatgaggtcgcctgatttcttagtttaatggtttagaaagaatatcttcttctttgtaacaatttatctacatatttttggtcaacctgatttataatttgataccattagaaacttagattgatattttgataccatgagttataaagatttatttatgttcataaaataaaatctcttagattatgaatggttaattcggttttggtttaaatttgattttatgaaatttattaagtttgtggtttggtttattttcagcttgatttgctatatccaaacgatatatagttggctcatatattttgtctatttagaagatcatttacggacaatgatacataacctctaattgtttgtgctaattaaatggtttctacatgtgatttccatatactcccgacagtactaaatctagcaaaacctaacatttcctacgaaataagtcaataacatgtgtgttatatttgtgttgtttatctttaggtacatgagagatatcaaagagttcgaagctaaattacgatgggttgtaggtgtggatgttcaagttaatcaattggcagatatcaaagaagtcaaggccaagatgtctgaaatcagcactaaacttgacgaaatcatgactcaaccaaccgaagc"
dH(x,y)

# test3
# output should be 733
x = "ccttcaagaggccgtcaaaagagcaaaagatagatctgtaaccacaagattcatcttacaccgtctcgaagctacaatcgatactatcactccgttgattgttaaaattgataagttgagtgaaaaaatggaagattcatcatcgaggaaattcaatgaacgtcttaagcttctccttgtgaacgctgtttctcttgttgaggagaatgcggagctgagacgcagaaacgtacgcaagaagttcaggtttgtgctaaatagttcctatatgtgatttccataaactcccaacagtactaaatctatcaaaacctaacatttactatgaattaagtcaataacatgtgtattatatttgtgttgtttatctttaggtacatgagagatatcaaagagttcgaagctaagatacgatgggtggtaggtgtggatgttcaagttaatcaattggctgatatcaaagaactcaaggccaagatgtctgaaatcagcactaaacttgacaaaataatgcctcaaccgaagtcctccacgaggccgtcaaaagagcaaaagatagatctgtaaccacaagattcatcttacaccgtctcgaagctacaatcgatagtatcacaccgttggtggttcaaattgataagttcagtgaagaaatggaagattcaacatcgaggaaagtcaataaacgtcttaagcttctccttgagaacgctgtttctcttgttgaggagaatgcggagctgagacgcagaaacgtacgcaagaagttcaggtttgtgctaaatagttcctatatgtgatttccataaactcccaacagtactaaatctatcaaaacctaacatttactatgaattaagtcaataacatgtgtattatatttgtgttgtttatctttaggtacatgagagatatcaaagagttcgaagctaaattacgatgggtggtagatgtggatgttcaagttaatcaattggctgatatcaaagaactcaaggccaagatgtctgaaatcagcactaaacttgacaaaataatgcctcaaccgaagt"
y = "gattggtgagcttgcgataggggctgttcttggagttggagcccaagccatttacgaccgcttcagaaaagcaagagatatatctttcgtacaccgtctctgcgctacaatccttagtatcgagccgtttttggttcaaatcgataagcggagtaaagtggaaggttcaccattaagggaagtcaacgaacgtctcacgtgtttccttgaattagcttatgtttttgttgaggcttatccgaaactcagacgcagacaagtactcaggaagtacaggttcgtatatatgacatgaatttctattggtttttggatcgcttaatttcttagtttaatggtttagagaaaaatatcttcttatttgtaacaattttttttacatgatttcgataatctccaaacactaaacgtacaaaacctatcatgttgtggaaaaataacacgtgtattatgtttgttctgtttatctttaggtacatcaaagcaatcgaaacgatagaacttgcattaagaagcataatagttgtggattttcaagttgatcaatgggacgatatcaaagaaatcaaggccaagatatctgaaatggacactaaacttgctgaagttatttctgcttgtagtaaaataagagcttgattaaaaaaaacagagactttgttgaaattatttcttcttgtaatcaatttcggaaatctatttctctctctctcttattccccataattattgaaaaactctttctcaatctatgtgtaattttatcaaaataataattaacaataatctttttatttcgtttcttttgagatctatgtttcatgatttttttttttttttgcataaattgaattaaattaactttgaaagacttgagtttaatgatgtttttactgacaatgatctaaaattgactttaaactatttgatttaattagctacaaaaaagtaaaagactatttaattttgttatttttagttgaattattaataatcatgtattgtttgtgatattaattatacttttgatatgatataatatttaactatttattaatatatattcgcttccaacgcataccgtttattaaattttttattaaaaaaatcgctttcacatttctagacgtttggctaccgcgtacatgcatctaattgcatggtacttcgttaccaagcggtccacacatctcttattcacactctttcgtaggaagttacggtaacaaataacatcccttgactgtacaaactacacggtttaattgttaagcaaaagactcttcaatagttccatgttcataaatttctccttacattcacctcagagagctaacaaactaatttcaagaagatgattgctgaggttgtggcagggggtgctcttggacttgctctcggtgtccttcacgaggccgtcaaaacagcaaaagatagatctgtaaccacaagattcatcttacaccgtctcgaagctacaatcgatagtatcactccgttggtggttcaaattgataagttcagtgaagaaatggaagattcatcatcgaggaaagtcagtgaacgtcttaagcttctccttgagaacgctgtttctcttgttgaggagaatgcggagctgagacgcagaaacgtacgcaagaagttcaggtttgtatatattacatgaaaatccatgtatttctattggttttttatatatatgaggtcgcctgatttcttagtttaatggtttagaaagaatatcttcttctttgtaacaatttatctacatatttttggtcaacctgatttataatttgataccattagaaacttagattgatattttgataccatgagttataaagatttatttatgttcataaaataaaatctcttagattatgaatggttaattcggttttggtttaaatttgattttatgaaatttattaagtttgtggtttggtttattttcagcttgatttgctatatccaaacgatatatagttggctcatatattttgtctatttagaagatcatttacggacaatgatacataacctctaattgtttgtgctaattaaatggtttctacatgtgatttccatatactcccgacagtactaaatctagcaaaacctaacatttcctacgaaataagtcaataacatgtgtgttatatttgtgttgtttatctttaggtacatgagagatatcaaagagttcgaagctaaattacgatgggttgtaggtgtggatgttcaagttaatcaattggcagatatcaaagaagtcaaggccaagatgtctgaaatcagcactaaacttgacgaaatcatgactcaaccaaccgaagc"
x = x[0:1000]
y = y[0:1000]
dH(x,y)
