"""
Given: An RNA string s corresponding to a strand of mRNA (of length at most 10 kbp).

Return: The protein string encoded by s.
"""

def translate(s):
    # Set up translation table
    RNA_codon_dic = {
        "UUU":"F", "UUC":"F", "UUA":"L", "UUG":"L",
        "UCU":"S", "UCC":"S", "UCA":"S", "UCG":"S",
        "UAU":"Y", "UAC":"Y", "UAA":"STOP", "UAG":"STOP",
        "UGU":"C", "UGC":"C", "UGA":"STOP", "UGG":"W",
        "CUU":"L", "CUC":"L", "CUA":"L", "CUG":"L",
        "CCU":"P", "CCC":"P", "CCA":"P", "CCG":"P",
        "CAU":"H", "CAC":"H", "CAA":"Q", "CAG":"Q",
        "CGU":"R", "CGC":"R", "CGA":"R", "CGG":"R",
        "AUU":"I", "AUC":"I", "AUA":"I", "AUG":"M",
        "ACU":"T", "ACC":"T", "ACA":"T", "ACG":"T",
        "AAU":"N", "AAC":"N", "AAA":"K", "AAG":"K",
        "AGU":"S", "AGC":"S", "AGA":"R", "AGG":"R",
        "GUU":"V", "GUC":"V", "GUA":"V", "GUG":"V",
        "GCU":"A", "GCC":"A", "GCA":"A", "GCG":"A",
        "GAU":"D", "GAC":"D", "GAA":"E", "GAG":"E",
        "GGU":"G", "GGC":"G", "GGA":"G", "GGG":"G",}
    
    # Scan for triplets in protein s and add them to prot string
    prot = ''
    for i in range(0, len(s), 3):
        start = i
        stop = i + 3
        if RNA_codon_dic[s[start:stop]] == "STOP":
            break
        prot += RNA_codon_dic[s[start:stop]]  
    return prot


x = "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA" 
translate(x) # expect output : MAMAPRTEINSTRING

y = "AUGUAAGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA" 
translate(y) # expect output : M

z = "AUGACUCUCGCCUCAUCGGAGUCAGGAAGUCACCUUAGACGGAGCGUAGUUGAUAGACUGGAGACAGUAGUCUAUGCCGCUGGUGCUGACAUAUAUAUAUGUUGCGUCUGUACCUGUCAGCUCGGACCAGGUCUAUUAGUGGUGCCCAUAGUGCGGGUCCCAGUUAGUUUGUCCGCAUGCGAUAUAUCCAGGCACCUACCCCCUUCCAACAGCGACUCCAAUAGAUCUUAUACAACGCCGGCAUGUUACACCAACUUUUUAAAGUUCCCGGUACCCCGAUCCCGCUCCACGUUCCGAGGAGCAGAUAAACUGCAAACGCGAAGAAAAAGGAAGGCUAGGGCUUCGUACGAUAAGGGACAUUCUCAUGACCGCGAGCUAUAUCGCCCCGAUGGUGUGUCCAAAGUAAUUGACCGUGCAGCAGCAACAUGUCCACCAGAGUUAGCUAAUUACUUCUGUGCUAACACCUCGAGGAUCCGCCGCAAAAACCCACACCACUGGAAAGGUUCGAGCCCGGGCGAUGUAGGCGCACCGAAUCAUUGUCGGACUGAAUACGGGUUUGUUAAGUGGUUGCUGAAGGGGGAGCCGAAAUCCUCCUCUGGCCACGAGUACCACCGUCUCCAAUGUCUCGGCACCGUUCAGCGUCUUACCGACGCGGAUACGAUGAACAGCCCGCUUAGCCUCGAAGGGCCCCCAAGACAUGCAUUGACUUUCAACUUUGCCCGCUCUCUCCGACACACUGAGAUCUCCAGGUCGAAUCACCUAGGUACUGUAUCACGGUUGCAGGCACGUCCAUUUCCUUGGGUAGAACAGUCGACGAGCUCAACUAAGCUCUCGACUAUCGCGACUGAGUGGGAACGCCACGCACAAUCUUACUACCUAGAUUUUAUAUGCUGUUGUUUCCGCAUGUACAGACGACGGGAUGGAGGGCUUGUAGCUCUGAGGGAGACCACUGAAUUGAUUAGCUUCGAUCAAAAGCGGGUGCUCAAGCCGGAAUCGUCCCUUAGGCCGACCAAAGUGAUACGAGUUACGCAGUUCCGUUGCAUUUGGGAUCUUUCCUGUAACGAACCGGCGACCCCAUUCCCGUUCCCGCACCUCACGCUACGAUUACCGAGAGAUUCCCAUUUGUGGAUGUGUACUAACAAAACGAGGCGUGAAUUUGAGACACCAGUUGCCCUGUCUUUAACUAGACUCAUCUUAAAUUGUCCCUACUCCAAACGCAGUGCAGUUGCCAACCGCCUUAAAGCUUAUUCGUUCGAUGCAUGGUUGGACCGGGAGGAUGCGCUGUUCACCGAAAUCGGUAACUGUCCGGAUUUUGUGACCCAGGUACGUCGAGGCAACACCUGCCGGGCCAAUGCUCGUGUUUCGACACUCACGCGUUUCGAUCAUCUCGCAGCUAUAGUGCACUCAAGCAUACUUCCGCGAACAUGUAAAUACUUCAGACUCAUUUUCAGCGCGACCGAGUACACCACAGUUCUACCCUUUCUUUCGUCUAUGCAUGUCCAGUUGUUGGGGCCAAUUGCGAAGUGGGUUGCUAGUUCGCAACAUUCCAAUUUCACCUUACUCAAGGCGUGUAACAGAUAUCAGGCAUUUAUGCCAGGACAAUUGAGUCUCGCAGAUAAGAGUGACUUGUUUUUGGGCCUGGCCCCAACCCGACGGGCGGCCUUUCCACAGAAUGCGUGGAAUAUCAUGCUCGCUUCUUCCGACCAUAAAUUCGUGCGAGGACGAAACACUUCAUACGUUGCCGAGUGGCGUGUCAGGGACCGGGUAAAGUUGUUCGUCGCUAGAGGUCCUCCACACGUAUUCGCUCCCACCCCUAAUGCCAUGAAUAAAACUGGGCGUAGGUCGUUACGUUAUUUUCAUGGGUAUUCGCUCAGCAUGACUGGGCCACCCUCACAGGAGGUGGGCCAGGUUGGUCGCCCUUAUAGCUCUCAAGUAACACUAACUCCAUGGAUUUGCAAGGUGCUCAAUAGGCGGCUUGCACAGCUACGGGUUGCUUCGAAUGGCCAUAGGCGUUUUUUAUUGCCGACAAGUUCCGUAUUGGGAAAAAUAAGAAUUGAUAGGAUGGUAAGGGUAGAGACUGGUUACCAGCAAGUUGUACUGUAUCGGCGAUUUUCAUCGGGGACAUUGAGUCCAACACAGCCUAGCAUGCCGCGGGGUAGGCAACCGUUAUGCAUUGAUAAAGAUCGGACGGCGGAAGUUGGUUUCGGGAUUACAAGAAGAGGACCAAGACCUGUGUUUUCAGCGCCAGGGGUACCGUCCUGUGGUGGGAAUCUUUAUUUUUUUCAAUCGCACAGUACGAGCUUGGAUCUCGGCCAUCUCCUAUUGCCGAAUACCAGUGCUAGUAUCCGUUCACAAGGGGUUGCAAUGCGUAACCUCACGUCGACUCCUCGCCAGGCACAGCGCUCGCGGAGACAUGUCUUGCCCAAAACCGACGUCAAAUUCAUUUCUCGUGUUAAAUCAGGGUGUCACGUAAUCCACCUUCAUGCCUUGAGGACUUGCCAAUGCGAGAACUCGACUGGGGUCAGCGAAGUCCUAGUCCAUAAGCACGCGGAUAAUACAAUGUCCCUCACUCCAUCCAUGUGGCUCGUUACGCUCACCGGGAACGACAUGCGAUUCCUCUGGCUAGGGUUGGUGCGUUGCCUUUCAGAUAUUGCUGUCGGACUGCAGUCAUUAGCCAGUUGCAAUUACCCGUAUCCGAACAGUUGGAGUCUGGUUUCCAGGAUCAGCUGGGCGGGUUACGUAACGGACCUGAUUGCCUCACAUUACAAGGAAGACCGUCUACGAACCCACGUGUUCGUGUCUCGGUCCUCCUUCGUGGGCCGUCGCGCGGUCACCUCGAAACAACAACGUAGGGCGAAAAGCACAUGUCUCGCGCAGGUCGGGUUUACGUGUGUACGCAGGUCGUCGUCUAAUGCGGGACCAGCGUUAUAUGGCACUGGCGUGAGAAGAUUGGUUGCUGACUUUCAUUGCGAUGUUUUUCCCGCUAGUGUUCAUACCGAUGCGAAGACCCAGGGCCCGUUAGUACGCAACCACCCCCGAUUCAACGGGAUGAACGAGAACCUUGCGGAACACAUUUACGCAUACCGAAAAUUAUCCGUCCGCAUAGUCUGGUGGGUGUCAAGUGUUGUUCCAGCUACGUUUAUGGAAGAACGAAGGUUUGUGAUGGCCCCACGACAGCCCCGUAAAAGUUCGCGCCUUAGACAAAAUCCUGGACCGGUCACCGAUGUCUCUCUGGUAUACUCGUCCAAGAUCCUAGGAGGCUCGGUUUCGACAUUUGUAGAAUAUGUUGCAGCCAGGAUGAAGGCUGUGAGCCCGUCACUCCACGAGACUGUAGGCUGGCACCGUACACAUGUACGAAGUCCCGCAGUACCCCGUGUGAUGUCGACUGGACCGCACCAAUGUAAUACUCAUAAGGGCCUGUCGUAUCGUCUCAGUCCACCUCCAGUUUGUGUAGGGAGCUGCUUAUAUGGAUCUCUUAUGAGCGCAGCCUUUCUAGGUGUCACAAUGUACCUGUAUAUCAAUGGACAUGACACUAUAGAAAACAACAGACAAGUCAUUGAGGCGAGCUCACAACACGUUAGGUCUUCUCGACUCAUCAGUUGGGGCGAGGGGCUCUUGUCACUCAGAUCGCCGUCAAAGGGCGACACUAUGCCGCUCCUAGUGCGCUACCGCGAGAAUUCCAAAUCGACUCAUUCACGUAGGAUCCACAUCGCAUUCUGUCUGUCCGUCACUUGUAUCGUAUCCCCACAAGGCUCGAAAGGCUGCGCCGCGUGUUCUCUUCGUCCCGAUGGGAGUUCUAGACGGAUCCAUGAAGGCCACCUAACUAUCUACGGGUAUGAAUUGGUCUCGGCGGUGUUGACAGAUUGGCCCUACAAAUGCGUUAGUGUGUCCAGGGUUCGUGAGCCACGCAAACCCCUUAGACACUUCAGGCUCUCGAGAAUUCUAGGAACCGACCGUGGGUGCAUGGCAUCUGGCGUCAAUGGUGGGCUUUACCGCAACUGGGAGCUAUCCGCAAAACACAAUCUUCGGAAACGUGCACCAGCAGCUAGUCUGUCCCAAAAUAGCCAUCUCAUGGGAUUACCUGUAUCCUGGCAGUACUUAUCGUUUCUGGUAAGGCCCUACUGCCACACUGUAGAGCAGAGAGACACUGUCCCGUUAUUGACAAGAAACGUUUAUUGGCAUUGUAGGUCAAUCAUCGCCGAACUUAAGGCAUUGCUCUACUUAAGGCUCUUUUGUGACGCAUCCUGCUUGCAUGGAGAUGGUUCGUCAGAACUGCGCAAUACUUUCGCAGUGGCAGUUCUGGCUACGUACUUGUUUCAGACGGUUAGCCUGUGCACAUGGUUAAUCGUACCAGCACUCGAUGUGUGCGCAUCACGUGCUCCGCUUAAGUACGUCGAAAACCACUUAGAAACCGGCCAUCGGGAUAAAGGUGCUAUGCUUCCUCAUACGUUAUCUAUGCCCAGAUCAGGUGCAGGCACAUUAGCAAUUACUCGUUGUAUACAUCCGCUUUGGCUUUCUUGGCUACUCCGAAAGCCAAUAGCUCGAUCCCAAAUGAUCGUAUAUGCGCCGCUUAUCUCGUUUCGUCACCUUUGGCUUUGGGUCAAAUACCUGAAAUUGAGUCGUAUCCACCUUCCUGCGAACCUUCAUAACAGGACGGGGACCGCUGUUCAAGCGUCCCUCUCUAAGGGUUCUGAAGAUGCGACAGCCUAUGAGUCAGUGCAGGCACGGGUCCGAUGCAGCGUGACCACCAAUCGUCAUCUUGACCGACCUCUGUUACAGAAUCCGACCGUGUGUUUGACAAAUACUCGCAGGGGUCGAAGUUCAGAUCGCGUGACGAGACAUAGACUCGAGACCGGGAGGAUUCCGCUGGGACCAGUUCCGUCUCGUGCGAAGAUGGCACGUUCUAUUGACGGUCGCGCAGUGGACGUUAUCUCCAACACUGAACAACCGCGUCACACAGUGCAUACUACGAUGUCCAUUCAUCCCGCGGAUGCUACAGACCAAAGACACAUUCAAAUAACGCUCACCAAGUCCAAGGUUAGCGUCGUGGUCCUCCACGUGUGUAUGAAGAUCCGAUACGCAGUGAGUGCACGAGAUCCUGUAAGCUGGGAAGAUACUGGCCGUACAGACUUCGCGUCUUCCUGGUAUAAUGGUUGGGCCACGUUAAACUUGUGCGCGGCUAGCAACGCGCCCAAUGGAGAGACUGGAUGUUUUAUCCACUUUCGACGUGCAGGAAUCCCCGGAUACAGGAAGCUACGGCUAAGCUCCACGUCGCACCCAGUCAUAUUGUGGCCCUCUGUAGAAUCGUUUGAGAGAAACCUUCUGACAAUCUACUGUCACGUGCUAGGAGCCCACUCGGUCCAUGAUGCAGUUGAAUUCGACUUUUUACCCUCGACUCAACGGUCUUGCUUGACUUCGGCCCCUUUAAAGAGUGGCCUAAAGUUGGCCAUAAGACACACUUUCCGGCUAGCACGGCGCGGCCCGCGUCAUCAACUACGGCCGUUCUGUCGCGUGACGCCGCUAGUGUGUAGGAUCAACACUGAUAUUGAGGGUAUCCGAUUGCCUAAGCGAGAGAACAUGCUGGAUAUCCACCGUUGUCUAUUCACUUACCGGACGGCGACUUCCAUGACUCGGCUAAAAAGAGUAUGCGACGUCACGGACACAACUUACAUAUUAUCCUGGAUUGUCGAAUUGGCUCUAUACGUAGCGAUUAUUUGUGGGCGAAGACAUUUACCCGCAGAAUCCACUAGUCCUUGCAGCCGCGUCUUAGGGGCCUCAGUUCAUAGAACCAGGGCGGCCUUAGAUCGCCGUAUUCAGCCAUCGGGCGCGAGGCCUUCGUUCCCCUUGAGCCUGCAAAUGGCCCGGGCGGGGCCUAUGAGAUUCGCAACUCACAAGGGUGGUUGUCGAAUUGUAGGUUCAGCCGAGGUCCCCCCCUCAACCGGACCUCGACUUGGUCUUGAACAAUGGGACGGCUAUCCGAGUGGACUUGCUUGGAUUCCCGAAUCAUAUGUUAGGAAUGACGGGGGAAGAUAUAUGGCUAUACCCCGAACGAACCCCAAUUGGCUCGUUGUAGACGAAGACAGUAGGUGUAGAUCAUGGCCAUUAUGUAGAUGCCUAGUGUCUCACUCAUGGACUUUGCUGACGUAUAAAAUCGCACGGUUAAAACGCGGCUUUGUGCGGCAGUUUAGUGAAGCAAUCAGAUGCAGGGUACUAUUCCGGUGCAGGCCCGCAUGGCGUCAAUUGUGUCCCGACAACCGCUGUUCUGUGUUUGGUCAUCAUUAUCUCCGUAAUUUCGCGACGGCAUUACGUACGGCUCGCGGCGACUGUAAUAGCCAUUGGUUACGCAGCGCAGACUUAUCGGGCGUCGGUGAACGAACGAGCUCCUCAACAGUCGCAGCGGGGAACCCUCAAGUGUUUCUGUCUCCGUCGUGCAGUCAAGAGGCAAAAACGGUUGAGCCGUCAAUUAAUUGCCUAGGCGGUUACCUACCUCUGCUCGGGUCCCGCCUUGGGUCCAAUUACGCAUCUACCCUUGAUCAUUUAUCACCUGGACGCAAUACAACGCACGUAUACACAUCUAGUCAAGGCCUUUGCCUGCCGCGGCUUUUCAUCGUGAUAUGGCAUGAUCGGGGUAUUGGAAACUUAGUUGGAAUCAGCUACUUCGAAAUUCGGGAUUGGUCUGUCAUUAUCAACCUUGCUAAAUUCCGCGAGCCAGCUCCCUGUCUGUGGUCCAUGCUUGUCCAAGUUAUAGGCUACUGGGCAAAACAGAAUAAAUGGACUGCUUUUAGAUCAUCACGAGGUUCGUUGCCUAAGUGCGAGCAGAACCUGUGGCCAGCGGCUGGACGAUGGAGCGCGGGGACCCCUACGCUGGGAGCUCGGGAGCACGGGUCGUUUUUCCGCAAGUGGUUAGUAGGCUUUAUGGUGAUUGGGUUCGUAGGGCAGUAUCUCCGGUAUCAGACGACCGAAGGUAGGAUAGGGCGGACGGUGGCCGCUUGCUUUGCAAGUUUGAACCCAUACGACUGUGUGUUUCUCAAGCGGAGUCGGGUAAUGUUUUAUAGAAACCUAUUUGGCUGUCUUCACGGGCAGCCCAAUCCCGUCGGUGCCUGCAGAGGCGGCGGGGGGUCGUCGAAAAAGGGCAAAAUGGUGGUGCUUCAUGUCAUAUCUGUACUGCAGGAGAAGGGAACCUCUAAAUUCGUUGCAGAUCCUUGGAGUUUUGAAUUCGACCAUAGUCACACGACCUUGUCCCUGUGUUGGUGUAAGACCAUUCGAAUGAUCUCAGUGACUCCGAGACCUCGCUCGAAACGUUGCUUUACAUCGAACAGAGGAAUCGAAUCGUCGGCGUUAUUAGUAUCUACAUUACUCUUGUUUACCGCCAUCGGCUUUAGAACUUGUGUCGGGCGUCCGAUUCGAAUGAAUGUCACUGGUGAUUGUCCUGCAAUCGCGCUCUACUCGACUGGUCGUCAUGCGUCUGACUCAGCGUGGCGCGCGGUGUCGCAGCUACCGCAGUGUUCAAGUAGCACCAUGAGUUACUCAGGUAGCGUCUUCCACGACCUAGUAUCCUCAGUACCUAGCUCUAAGCCCCUACCGGAACGGUUUAAACGGCCGACGAUGAUGCUUCGAUUGGCCAGCUCAGGCUUACAGAACGCUCAUACUAUGCAGUCCGGGUCAUAUGUAGCACUAUUUUCGGGUGCACCAUCAUUUUGCAAUCCCGAACUGAACUCGCGUUUUCGGUCGGUAAGUAUAAUCCGACCCGUAGUACUUAGUCAACGAUCCUGGAUGAUAGGAAAGCAUCAGGGAUGCAUCACCGACAGUGAAAGUACUUGGAAGGAACUGGCCAUGGCGCACGGGGGCCCUGGGUGUGUAACUAGAACAGACUUGUUCUCCCCCUUUGUAUCGUGUCUGGUGGGCCUAUCUACUGGCCACGACGAACGCACAAAAACCGAAUACACAGGCACAAACGCGUGUAUGACCAGGGACUCUAGGCGACUCAACGUAGGACCUAUGUUGUGGCCGGGCAGGAGGGUUACCGACUACCAUUGCCAAGCCCUGUUCAUACUGGUUACCCCAGUAUCGGGCCAUAUAAUUCGUCAACGACGAUCAAGAACUCUUUCGGGACUUGGCGCAUGGUCAGAACAACUUAGUUCGGACAGCGACCGAGACUGUGGACACAUGAGGAGGACAGCCUACCAGAUCUAUCCUAAUUGCAUAGAAACUGGGUUGAGUUGGCGCUCUGCGAAUGUCCGGGGAAUAAAGACUUAUAACUCUUCGAUGGAAGGGUUAGAUUAUCCCUCGUCAAUCACGAUGAAUCUUUUGCGCCCUGGUGCCCCGUUUGUAGGCAUGACUCAUAAGCGUGGAACCCGGGCUGUUUCGAGCAGUUCCUUAGCCUCAAACAACCUGAUCAGGGUAGGCAUCUUGGGCUGGAGGACCGAGGGAGUUACAGGUAUGGAGCAGCGCAAGUAUCACACGCUUGAGCGCGGCUAUAACGUCUCGUGGAGAUCUGCAUCCCUUGGUGAUCUGGGCGGAAACCUAUACGAUACGAGCCGGCAAAGAAUGAUUGCUCAAAUUACGGAACAGCCUGCGACAAUAACGCGAGCUGUUACCUGCGUAAGCGGCGACGUUCAUUCAAACAGUUGUGCUCUGACAAUAUUUACUAAGGGAGCAGCACCAUCGGCGUAUGACAGACAAACUCGGCACUGCCUACGUGCUACGAAUCAAUCCGGGUGGAGCUCAGUCGGCCCCCCACCGAACGCUUUGCUUUUUACCCUGGAAACAGCUUUAUGUUGA"
translate(z)

# Genius solution to format codon table in Rosalind by Ben Usman

# Copy the entire table unformatted 
string = """UUU F      CUU L      AUU I      GUU V
UUC F      CUC L      AUC I      GUC V
UUA L      CUA L      AUA I      GUA V
UUG L      CUG L      AUG M      GUG V
UCU S      CCU P      ACU T      GCU A
UCC S      CCC P      ACC T      GCC A
UCA S      CCA P      ACA T      GCA A
UCG S      CCG P      ACG T      GCG A
UAU Y      CAU H      AAU N      GAU D
UAC Y      CAC H      AAC N      GAC D
UAA Stop   CAA Q      AAA K      GAA E
UAG Stop   CAG Q      AAG K      GAG E
UGU C      CGU R      AGU S      GGU G
UGC C      CGC R      AGC S      GGC G
UGA Stop   CGA R      AGA R      GGA G
UGG W      CGG R      AGG R      GGG G"""

coded = "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA"
decoded = ''

# Split string by white space
traL =  string.split()

# Zip the codon-AA pair and represent in dictionary
traDict = dict(zip(traL[0::2], traL[1::2]))

for i in range(0, len(coded)-3, 3):
    decoded += traDict[coded[i:i+3]]

print decoded

