'''
Given: Two DNA strings s and t (each of length at most 1 kbp).

Return: All locations of t as a substring of s.
'''

def substring(pattern, seq): 
    # time = O(len(seq))
    for i in range(len(seq)):
        if seq[i:i+len(pattern)] == pattern:
            print(i+1)

s = "GATATATGCATATACTT"
t = "ATAT"

substring(t, s)

s = "CCCTCTCCCCTCTCCATTCTCCCTCTCCTAGCCCTCTCCACCCTCTCCCCCTCTCCCCTCTCACCCTCTCCCCTCTCAGTCCCTCTCCCCCTCTCCCCTCTCCCCTCTCCCCTCTCCGGGGGACATACCCTCTCATGCAAAGCCCTCTCAACCCTCTCACCCTCTCATAATCCCTCTCCCCTCTCCCCTCTCGTACCCCTCTCCACCCTCTCAAGACCCCTCTCCCCTCTCGCCCTCTCCCCTCTCTCCCTCTCAGTCCCTCTCGTCCCCTCTCAGGCCCTCTCAGTATGTCCCTCTCCCCTCTCTCCCTCTCCCCTCTCCCCTCTCTAACCCTCTCGCCCCTCTCCTATTAAGCCCTCTCAATACCGGCTCCCCTCTCATCCCTCTCTCCCTCTCGATAACCCTCTCTATCCCCTCTCGCGCAACCCTCTCGGTTGTTTACCCCCTCTCTGGCCCTCTCCCCTCTCTATCCCCTCTCATCCCTCTCTTAAACCCTCTCCCCTCTCACCCCTCTCTTAGATCCCTCTCTAAATCCCTCTCCGTCCCTCTCCCCTCTCACAAACTCGGCCCTCTCACTGTCCCTCTCCCCTCTCGGTCCCTCTCCCCTCTCGCCCTCTCCGTATAGAACCCCTCTCACCCTCTCCCCCTCTCGTCCCTGAAACAAACCCTCTCCCCCCTCTCCCCTCTCCATGCCCTCTCTCTACCCTCTCTCAAGCCCTCTCCTCCCCCTCTCTTTCCCTCTCGTCCCTCTCGCTGAGCCATGTCCCTCTCCAGAAGTCATTGCTTAGACCCTCTCAATGGACCCTCTCTCAGCAGCCCTCTCTGCGCTCCCTCTCCCCTCTCTCAACCCTCTCCCCTCTCTGTGCCGCCCTCTCATATGGC"
t = "CCCTCTCCC"

substring(t, s)
